version: '2'

services:
  rabbitmq:
    image: rabbitmq:management
    mem_limit: 512m
    mem_reservation: 128M
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: 'postgres'
    container_name: db
    mem_limit: 512m
    mem_reservation: 128M
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  listener:
    image: smorenapi/listener:latest
    mem_limit: 512m
    mem_reservation: 128M
    build:
      context: .
    container_name: listener
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RABBIT_HOST=rabbitmq
      - QUEUE_NAME=myQueue

  # Additionally, you can run the producer container
  producer:
    image: smorenapi/producer:latest
    mem_limit: 512m
    mem_reservation: 128M
    build:
      context: .
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - QUEUE_NAME=myQueue
